import ConceptBlock from './ConceptBlock';

/**
 * ExampleDecision — documentation example mode (Phase 11F).
 *
 * Mirrors the structure of the live Explain Decision panel, but renders a
 * clearly-stamped static teaching example. It is never connected to the
 * engine and never presented as real evidence.
 */
export default function ExampleDecision() {
  return (
    <div className="border border-hairline bg-panel-1">
      <header className="flex items-center justify-between border-b border-hairline px-4 py-2.5">
        <p className="hud-stamp !text-[10px] text-[var(--color-text-secondary)]">
          WHY THIS DECISION?
        </p>
        <span className="hud-stamp !text-[8px] rounded-sm border border-hairline-strong px-1.5 py-0.5 text-[var(--color-text-muted)]">
          DOCUMENTATION EXAMPLE
        </span>
      </header>

      <div className="space-y-5 px-4 py-5">
        {/* Decision header */}
        <div className="flex items-center gap-3">
          <span className="font-display text-base font-semibold tracking-tight">
            Dispatch ALS-CBD-03
          </span>
          <span className="hud-stamp !text-[8px] rounded-sm border border-teal-core/40 bg-teal-core/5 px-1.5 py-0.5 text-teal-core">
            ADVANCED UNIT
          </span>
        </div>

        {/* Reason */}
        <ConceptBlock title="SELECTED BECAUSE" kind="intelligence">
          <ul className="space-y-1.5">
            <li>— Closest available advanced unit</li>
            <li>— Reaches the scene in acceptable time</li>
            <li>— Nearby emergency coverage remained protected</li>
          </ul>
        </ConceptBlock>

        {/* Alternatives */}
        <div>
          <p className="hud-stamp !text-[9px] mb-2 text-[var(--color-text-muted)]">
            UNITS EVALUATED
          </p>
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="text-[var(--color-text-muted)] hud-stamp !text-[8px]">
                <th className="py-1.5 font-normal">UNIT</th>
                <th className="py-1.5 font-normal">ARRIVES IN</th>
                <th className="py-1.5 font-normal">OUTCOME</th>
              </tr>
            </thead>
            <tbody className="tnum font-mono">
              <tr className="border-t border-hairline text-teal-core">
                <td className="py-1.5">ALS-CBD-03</td>
                <td className="py-1.5">4.1 min</td>
                <td className="py-1.5 hud-stamp !text-[8px]">▸ SENT</td>
              </tr>
              <tr className="border-t border-hairline text-[var(--color-text-muted)]">
                <td className="py-1.5">ALS-IND-07</td>
                <td className="py-1.5">6.8 min</td>
                <td className="py-1.5">passed over — slower arrival</td>
              </tr>
              <tr className="border-t border-hairline text-[var(--color-text-muted)]">
                <td className="py-1.5">BLS-EAST-02</td>
                <td className="py-1.5">3.9 min</td>
                <td className="py-1.5">passed over — lacks the required equipment</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="border-t border-hairline pt-3 text-xs leading-relaxed text-[var(--color-text-muted)]">
          In a live run this panel is filled only by engine-published evidence.
          Nothing here is generated by the interface.
        </p>
      </div>
    </div>
  );
}
